version: '3'

volumes:
  shared_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vagrant/05-virt-02-iaac/virtd-homeworks-main/05-virt-03-docker/data

services:
  centos:
    image: centos
    container_name: cent01
    restart: unless-stopped
    volumes:
      - shared_data:/data
    command: ["sh", "-c", "tail -f /dev/null"]

  debian:
    image: debian
    restart: unless-stopped
    container_name: debi01
    volumes:
      - shared_data:/data
    command: ["sh", "-c", "tail -f /dev/null"]